default:
  golem_name: shinylego
  golem_version: !expr desc::desc_get_version()
  app_prod: no
  feedback_repo: "rpodcast/shinylego_testing"
production:
  app_prod: yes
  feedback_repo: "rpodcast/shinylego"
dev:
  golem_wd: !expr here::here()
